name: Dependabot Auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-automerge:
    uses: chriopter/hugo-autopilot/.github/workflows/dependabot-merger.yml@main
    with:
      merge_method: 'squash'
