name: Dependabot Auto-merge
on:
  workflow_call:
    inputs:
      merge_method:
        description: 'Merge method to use (merge, squash, rebase)'
        required: false
        type: string
        default: 'squash'
      commit_message:
        description: 'Commit message template'
        required: false
        type: string
        default: 'pull-request-title'

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ github.token }}"

      - name: Debug metadata
        run: |
          echo "Update type: ${{ steps.metadata.outputs.update-type }}"
          echo "PR URL: ${{ github.event.pull_request.html_url }}"
          echo "PR number: ${{ github.event.pull_request.number }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
        
      - name: Enable auto-merge for Dependabot PRs
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          if [ -z "$PR_NUMBER" ]; then
            echo "PR number not available in context, trying to get it from the event payload"
            PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          fi
          
          if [ -z "$PR_NUMBER" ] || [ "$PR_NUMBER" = "null" ]; then
            echo "Error: Could not determine PR number"
            exit 1
          fi
          
          echo "Using PR number: $PR_NUMBER"
          
          # Use the correct syntax for commit message
          if [ "${{ inputs.commit_message }}" = "pull-request-title" ]; then
            # Use PR title as commit message
            PR_TITLE=$(gh pr view $PR_NUMBER --json title -q .title)
            gh pr merge $PR_NUMBER --auto --${{ inputs.merge_method }} -t "$PR_TITLE"
          else
            # Use custom commit message
            gh pr merge $PR_NUMBER --auto --${{ inputs.merge_method }} -t "${{ inputs.commit_message }}"
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}
