name: Hugo Autopilot Dependabot Merger

on:
  workflow_call:
    inputs:
      merge_method:
        description: 'Merge method to use (merge, squash, rebase)'
        required: false
        type: string
        default: 'squash'
      commit_message:
        description: 'Commit message template'
        required: false
        type: string
        default: 'pull-request-title'

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ github.token }}"

      - name: Debug metadata
        run: |
          echo "Update type: ${{ steps.metadata.outputs.update-type }}"
          echo "PR URL: ${{ github.event.pull_request.html_url }}"
          echo "PR number: ${{ github.event.pull_request.number }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
      
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --${{ inputs.merge_method }} "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ github.token }}
