name: Hugo Updater

on:
  workflow_call:
    inputs:
      hugo_version_file:
        description: 'Path to file containing Hugo version'
        required: false
        type: string
        default: '.hugoversion'
      update_branch:
        description: 'Branch name to use for update PRs'
        required: false
        type: string
        default: 'update-hugo'
      pr_title_prefix:
        description: 'Prefix for PR titles'
        required: false
        type: string
        default: 'Update Hugo:'

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Check Hugo version
        id: check
        run: |
          CURRENT=$(cat ${{ inputs.hugo_version_file }})
          LATEST=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | jq -r '.tag_name' | sed 's/^v//')
          
          # Exit gracefully if API call fails
          if [ -z "$LATEST" ]; then
            echo "Failed to fetch latest Hugo version"
            exit 0
          fi
          
          echo "Current: $CURRENT, Latest: $LATEST"
          
          if [ "$LATEST" != "$CURRENT" ]; then
            echo "NEEDS_UPDATE=true" >> $GITHUB_OUTPUT
            echo "CURRENT=$CURRENT" >> $GITHUB_OUTPUT
            echo "LATEST=$LATEST" >> $GITHUB_OUTPUT
          fi
      
      - name: Update version file
        if: steps.check.outputs.NEEDS_UPDATE == 'true'
        run: echo "${{ steps.check.outputs.LATEST }}" > ${{ inputs.hugo_version_file }}
      
      - name: Create Pull Request
        if: steps.check.outputs.NEEDS_UPDATE == 'true'
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Update Hugo from ${{ steps.check.outputs.CURRENT }} to ${{ steps.check.outputs.LATEST }}"
          title: "${{ inputs.pr_title_prefix }} ${{ steps.check.outputs.CURRENT }} → ${{ steps.check.outputs.LATEST }}"
          body: |
            This PR updates Hugo from version ${{ steps.check.outputs.CURRENT }} to ${{ steps.check.outputs.LATEST }}.
            
            ## Changelog
            See the [Hugo release notes](https://github.com/gohugoio/hugo/releases/tag/v${{ steps.check.outputs.LATEST }}) for details.
            
            *This PR was automatically created by the Hugo Updater workflow.*
          branch: ${{ inputs.update_branch }}
          delete-branch: true
          labels: |
            dependencies
            automated
      
      - name: Auto-merge Pull Request
        if: steps.create-pr.outputs.pull-request-number
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""  # No labels required
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          PULL_REQUEST: "${{ steps.create-pr.outputs.pull-request-number }}"
      
      - name: PR Creation Status
        if: steps.check.outputs.NEEDS_UPDATE == 'true'
        run: |
          if [ -n "${{ steps.create-pr.outputs.pull-request-number }}" ]; then
            echo "✅ Pull request #${{ steps.create-pr.outputs.pull-request-number }} created successfully"
            echo "URL: ${{ steps.create-pr.outputs.pull-request-url }}"
          else
            echo "❌ Failed to create pull request"
            echo "This could be due to no changes being detected or an error in the PR creation process"
            exit 1
          fi

      - name: Delete branch after merge
        if: steps.create-pr.outputs.pull-request-number
        run: |
          # Wait a moment for the merge to complete
          sleep 5
          # Delete the branch
          git push origin --delete ${{ inputs.update_branch }} || echo "Branch may already be deleted"
      
      - name: Trigger rebuild with new Hugo version
        if: steps.create-pr.outputs.pull-request-number
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: hugo-autopilot-build
          client-payload: '{"reason": "Hugo version updated to ${{ steps.check.outputs.LATEST }}"}'
